server:
  port: 8080

spring:
  application:
    name: ocsw
  profiles:
    active: dev
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceName: OcswScheduler
          threadPool:
            threadCount: 5

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

shiro:
  web:
    enabled: true
  loginUrl: /api/auth/unauthorized

logging:
  level:
    com.chen: info
